trigger:
- main

pool:
  name: MohitAgentPool555
  demands:
  - Agent.Name -equals MohitAgentPool555

steps:

# --- Fetch latest code from Git repository ---
- checkout: self
  clean: true
  fetchDepth: 1
  displayName: 'Checkout latest code from Git'

# --- Show checked-out commit ---
- script: |
    echo Current branch:
    git branch
    echo Current commit:
    git log -1 --oneline
  workingDirectory: $(System.DefaultWorkingDirectory)
  displayName: 'Verify latest Git commit'

# --- Show project files ---
- script: |
    dir
    echo.
    echo Checking package.json:
    dir package.json
  workingDirectory: $(System.DefaultWorkingDirectory)
  displayName: 'Verify React source'

# ---- Set Node.js version ----
- task: UseNode@1
  inputs:
    version: '18.x'
  displayName: 'Use Node.js 18'


# --- Install dependencies ---
- script: npm install
  workingDirectory: $(System.DefaultWorkingDirectory)
  displayName: 'Install React dependencies'

# --- Build React App ---
- script: npm run build
  workingDirectory: $(System.DefaultWorkingDirectory)
  displayName: 'Build React App'

# --- Verify React build files ---
- script: |
    echo ===== BUILD FOLDER =====
    dir "$(System.DefaultWorkingDirectory)\build"

    echo.
    echo ===== MANIFEST CHECK =====
    if exist "$(System.DefaultWorkingDirectory)\build\manifest.json" (
        echo manifest.json FOUND
    ) else (
        echo ERROR: manifest.json NOT FOUND
        exit /b 1
    )
  displayName: 'Verify React build files'

# --- Verify build output ---
- script: dir "$(System.DefaultWorkingDirectory)\build"
  displayName: 'Check build output'

# --- Package React build output ---
- task: ArchiveFiles@2
  displayName: 'Create Deployment Package'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/reactfrontend.zip'
    replaceExistingArchive: true

# --- Deploy to Azure Web App ---
- task: AzureWebApp@1
  displayName: 'Deploy React Frontend to Azure Web App'
  inputs:
    azureSubscription: 'MukeshServiceConnection555'
    appType: 'webApp'
    appName: 'MukeshWebApp1111'
    package: '$(Build.ArtifactStagingDirectory)/reactfrontend.zip'
    deploymentMethod: 'zipDeploy'